n =  1
i = 1
while n<=3:
    k = 1
    while k<=i:
        print("*",end="")
        k=k+1
    #print()
    #i=i+1

    t = 1
#i = 1
    while t<=1:
    #g = 1
    #while g<=i:
        print(" ",end="")
        t=t+1
    b = 3
    while b>=n:
        print("*",end="")
        b=b-1
    h = 1
    while(h<=1):
        print(" ",end="")
        h = h+1
    o = 3
    while(o>=n):
        print("*",end="")
        o = o-1
    r = 1
    while(r<=1):
        print(" ",end="")
        r = r+1
    q = 1
    while(q<=n):
        print("*",end="")
        q = q+1
    i=i+1
    n=n+1
    print()